//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDnevnik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diary
    {
        public int DiaryId { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public Nullable<int> Pupil { get; set; }
        public string Attandance { get; set; }
        public Nullable<int> Subject { get; set; }
        public string Homework { get; set; }
        public Nullable<decimal> Mark { get; set; }
        public string Details { get; set; }
    
        public virtual Pupil Pupil1 { get; set; }
        public virtual Subject Subject1 { get; set; }
    }
}
